### PR TITLE
Add `javascript` prefixed groups from javascript syntax

### PR DESCRIPTION
**Pull request by othree**
It will be great if general group name for JavaScript syntax can add to vim-jsx.
Based on the doc,
The group name should be filetype prefixed.
And all in lowercase. [Ref](http://vimdoc.sourceforge.net/htmldoc/usr_44.html#44.2)

### CODE REVIEW

**Comment by mxw** [comment]
@othree—What JavaScript syntax files are you using?  As the README states, vim-jsx depends on pangloss/vim-javascript, which does not include any syntax entities called "javascriptBlock" or "javascriptString".

**Comment by othree** [comment]
I maintain another JavaScript syntax myself, called [yajs.vim][].
I follow Vim doc's suggestion and use `javascript` as group name prefix.
There is another JavaScript syntax group name very common: `javaScript`.
Its because the syntax file for JavaScript provided by Vim use it.
But its not follow the convention.

I know this plugin's dependency is pangloss/vim-javascript.
But If you can support these two group name format.
Lots of JavaScript syntax can just work with vim-jsx.
ex: default syntax, yajs, jelera/vim-javascript-syntax (upstream of yajs).

[yajs]:https://github.com/othree/yajs.vim

**Comment by lazywei** [comment]
would love to have this be merged into master given i'm also using yajs like @othree 
Thanks! :beers:

**Comment by mxw** [comment]
Okay sure, this seems pretty reasonable.  Can you `git pull --rebase` over the most recent changes?  The syntax/javascript.vim file has been renamed to syntax/jsx.vim.

**Comment by othree** [comment]
Since I am not sure how to rebase on a PR.
I will resend another PR for the change.

**Pull request closed without merging**
